/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "eu-west-2",
  "aws_cognito_identity_pool_id": "eu-west-2:d15ec90d-239f-46f2-a927-8c14e0ba147f",
  "aws_cognito_region": "eu-west-2",
  "aws_user_pools_id": "eu-west-2_LExTFn2t0",
  "aws_user_pools_web_client_id": "5n3g5cjt1kerkml0advk1tq5iv",
  "oauth": {},
  "aws_cognito_username_attributes": [
      "EMAIL",
      "PHONE_NUMBER"
  ],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": [
      "EMAIL",
      "FAMILY_NAME",
      "NAME",
      "PHONE_NUMBER"
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [
      "SMS"
  ],
  "aws_cognito_password_protection_settings": {
      "passwordPolicyMinLength": 8,
      "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
      "EMAIL"
  ]
};


export default awsmobile;
